steps:
  - name: maven:3.6.3-jdk-11
    entrypoint: mvn
    args: ["test"]
  - name: maven:3.6.3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/GC_CustomBuilder", "--build-arg=JAR_FILE=target/GC_CustomBuilder-1.0.0.jar", "."]
images: ["gcr.io/$PROJECT_ID/GC_CustomBuilder"]