steps:
#  - name: 'maven:3.6.3-jdk-11'
#    entrypoint: mvn
#    args: ["test"]
#    id: 'install-dependencies'
#  - name: 'maven:3.6.3-jdk-11'
#    entrypoint: mvn
#    args: ["package", "-Dmaven.test.skip=true"]
#    id: 'packaging'

# Build the container image
  - name: 'gcr.io/cloud-builders/docker'
#    args: ["build", "-t", "gcr.io/$PROJECT_ID/GC_CustomBuilder", "--build-arg=JAR_FILE=target/GC_CustomBuilder-1.0.0.jar", "."]
    args: ["build", "-t", "gcr.io/$PROJECT_ID/GC_CustomBuilder:$COMMIT_SHA", "."]
    id: 'building'

# Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/GC_CustomBuilder:$COMMIT_SHA' ]

# Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'GC_CustomBuilder'
      - '--image'
      - 'gcr.io/$PROJECT_ID/GC_CustomBuilder:$COMMIT_SHA'
      - '--region'
      - 'us-east4-a'
      - '--platform'
      - 'managed'
images: ["gcr.io/$PROJECT_ID/GC_CustomBuilder:$COMMIT_SHA"]